# Generated by Django 3.2 on 2021-04-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=25)),
                ('visit_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'visits',
                'managed': False,
            },
        ),
    ]
